export const Generated_Form_Options = {
  // STEP 2
  category: [
    { label: "Technology", value: "technology" },
    { label: "Gaming", value: "gaming" },
    { label: "Finance", value: "finance" },
    { label: "Education", value: "education" },
    { label: "Fitness", value: "fitness" },
    { label: "Business", value: "business" },
    { label: "Entertainment", value: "entertainment" },
    { label: "Lifestyle", value: "lifestyle" },
  ],
  hookType: [
    { label: "Curiosity Gap", value: "curiosity" },
    { label: "Warning / Mistake", value: "warning" },
    { label: "Big Promise / Solution", value: "promise" },
    { label: "Before & After", value: "before-after" },
    { label: "Secret Revealed", value: "secret" },
    { label: "Emotional Story", value: "story" },
  ],
  desiredEmotion: [
    { label: "Shock", value: "shock" },
    { label: "Curiosity", value: "curiosity" },
    { label: "Excitement", value: "excitement" },
    { label: "Fear", value: "fear" },
    { label: "Confidence", value: "confidence" },
    { label: "Inspiration", value: "inspiration" },
  ],
  visualContrastType: [
    { label: "None", value: "none" },
    { label: "Before vs After", value: "before-vs-after" },
    { label: "Small vs Giant", value: "small-vs-giant" },
    { label: "Rich vs Poor", value: "rich-vs-poor" },
    { label: "Old vs New", value: "old-vs-new" },
    { label: "Human vs AI", value: "human-vs-ai" },
    { label: "Safe vs Dangerous", value: "safe-vs-dangerous" },
    { label: "Good vs Evil", value: "good-vs-evil" },
  ],
  subjectSource: [
    { label: "My Face (Upload Photo)", value: "user-upload" },
    { label: "AI Generated Person", value: "ai-generated" },
    { label: "Stock Subject", value: "stock" },
    { label: "No Person (Object/Text Only)", value: "none" },
  ],
  peopleCount: [
    { label: "0 (No People)", value: "0" },
    { label: "1 Person", value: "1" },
    { label: "2 People", value: "2" },
    { label: "Group (3+)", value: "group" },
  ],
  mainObject: [
    { label: "None", value: "" },
    { label: "Laptop", value: "laptop" },
    { label: "Smartphone / iPhone", value: "smartphone" },
    { label: "AI Robot", value: "ai-robot" },
    { label: "Money Stack", value: "money" },
    { label: "Gaming Controller", value: "controller" },
  ],
  facialEmotionLevel: [
    { label: "Natural", value: "natural" },
    { label: "Expressive", value: "expressive" },
    { label: "YouTuber Style", value: "youtuber" },
    { label: "Extreme Reaction", value: "extreme" },
  ],
  cameraFraming: [
    { label: "Close-up face", value: "close-up" },
    { label: "Half body", value: "half-body" },
    { label: "Full body", value: "full-body" },
    { label: "Object close-up", value: "object-close-up" },
    { label: "Split screen", value: "split-screen" },
  ],
  viewerFocus: [
    { label: "Subject's Face / Emotion", value: "face" },
    { label: "Specific Object / Prop", value: "object" },
    { label: "The Bold Text", value: "text" },
    { label: "The Environment / Scenery", value: "background" },
    { label: "Split Comparison (50/50)", value: "split" },
  ],
  visualEnergy: [
    { label: "Low (Minimal Clean)", value: "low" },
    { label: "Medium (Balanced)", value: "medium" },
    { label: "High (YouTube Style)", value: "high" },
    { label: "Extreme (MrBeast Style)", value: "extreme" },
  ],
  thumbnailStyle: [
    { label: "MrBeast Style", value: "mrbeast" },
    { label: "Clean Tech", value: "clean-tech" },
    { label: "Cinematic", value: "cinematic" },
    { label: "Gaming", value: "gaming" },
    { label: "Documentary", value: "documentary" },
    { label: "Meme Style", value: "meme" },
    { label: "Minimalist", value: "minimalist" },
  ],
  backgroundScene: [
    { label: "Studio", value: "studio" },
    { label: "Gaming room", value: "gaming-room" },
    { label: "Tech workspace", value: "tech-workspace" },
    { label: "Futuristic AI lab", value: "ai-lab" },
    { label: "City", value: "city" },
    { label: "Explosion / Chaos", value: "chaos" },
    { label: "Minimal solid color", value: "minimal-color" },
  ],
  sceneComplexity: [
    { label: "Minimal", value: "minimal" },
    { label: "Balanced", value: "balanced" },
    { label: "Busy / MrBeast style", value: "busy" },
  ],
  highlightType: [
    { label: "None", value: "none" },
    { label: "Arrow", value: "arrow" },
    { label: "Circle", value: "circle" },
    { label: "Glow", value: "glow" },
    { label: "Lightning", value: "lightning" },
    { label: "Fire", value: "fire" },
  ],
  textStyle: [
    { label: "Clean", value: "clean" },
    { label: "Bold", value: "bold" },
    { label: "None", value: "" },
  ],
  colorMode: [
    { label: "Bright YouTube", value: "bright" },
    { label: "Dark Cinematic", value: "dark" },
    { label: "Neon Tech", value: "neon" },
    { label: "Warm Emotional", value: "warm" },
    { label: "Brand Colors", value: "brand-colors" },
  ],
};

// Data for Visual Presets in Step 1
export const VISUAL_PRESETS = [
  {
    id: "none",
    name: "Custom / None",
    emoji: "✨",
    gradient: "from-zinc-100 to-zinc-200 text-black",
    border: "border-dashed border-zinc-400",
  },
  {
    id: "mrbeast",
    name: "MrBeast",
    emoji: "😱",
    gradient: "from-cyan-400 to-blue-600 text-white",
    border: "border-transparent",
  },
  {
    id: "ali-abdaal",
    name: "Ali Abdaal",
    emoji: "📚",
    gradient: "from-orange-100 to-orange-300 text-black",
    border: "border-transparent",
  },
  {
    id: "ishowspeed",
    name: "IShowSpeed",
    emoji: "🐶",
    gradient: "from-red-500 to-red-700 text-white",
    border: "border-transparent",
  },
  {
    id: "finance",
    name: "Finance",
    emoji: "📈",
    gradient: "from-emerald-400 to-emerald-700 text-white",
    border: "border-transparent",
  },
  {
    id: "tech",
    name: "Tech Review",
    emoji: "💻",
    gradient: "from-zinc-800 to-black text-white",
    border: "border-transparent",
  },
  {
    id: "gaming",
    name: "Gaming",
    emoji: "🎮",
    gradient: "from-purple-500 to-indigo-800 text-white",
    border: "border-transparent",
  },
  {
    id: "podcast",
    name: "Podcast",
    emoji: "🎙️",
    gradient: "from-zinc-200 to-zinc-400 text-black",
    border: "border-transparent",
  },
];

// Data for Quick Palettes in Step 9
export const COLOR_PALETTES = [
  { name: "Neon Cyber", p: "#00FFCC", s: "#111111" },
  { name: "Beast Energy", p: "#00E5FF", s: "#FF00E5" },
  { name: "Trust", p: "#10B981", s: "#0F172A" },
  { name: "Minimal", p: "#FFFFFF", s: "#27272A" },
  { name: "Danger", p: "#EF4444", s: "#000000" },
  { name: "Warmth", p: "#FDE68A", s: "#78350F" },
];
