export const DEFAULT_USER_THUMBNAIL = {
  id: "preview_1",
  title: "My Awesome Video Title",
  author: "My Channel",
  views: "0 views",
  viewsNum: 0,
  time: "Just now",
  duration: "10:00",
  color: "#a855f7",
  isPreview: true,
  image: null,
};

export const YOUTUBE_DATA = [
  {
    id: 2,
    title: "Is This Proof That Hans Niemann Cheated?",
    author: "GMHikaru",
    views: "1M views",
    viewsNum: 1000000,
    time: "3 years ago",
    duration: "14:57",
    color: "#71717a",
  },
  {
    id: 3,
    title: "Build a Modern Dashboard with React & Tailwind CSS",
    author: "CodeMaster",
    views: "220K views",
    viewsNum: 220000,
    time: "3 months ago",
    duration: "24:10",
    color: "#a1a1aa",
  },
  {
    id: 4,
    title: "Minimalism in UI/UX Design: A Complete Guide",
    author: "Design2Code",
    views: "550K views",
    viewsNum: 550000,
    time: "1 year ago",
    duration: "18:20",
    color: "#3f3f46",
  },
  {
    id: 5,
    title: "Figma to Next.js - Full Course for Beginners",
    author: "WebDevPro",
    views: "89K views",
    viewsNum: 89000,
    time: "2 weeks ago",
    duration: "1:14:57",
    color: "#27272a",
  },
  {
    id: 6,
    title: "Learning the King's Gambit with Hikaru!!",
    author: "GMHikaru",
    views: "308K views",
    viewsNum: 308000,
    time: "2 years ago",
    duration: "14:57",
    color: "#d4d4d8",
  },
  {
    id: 7,
    title: "STREAK ONE - 55 IN A ROW!!!",
    author: "GMHikaru",
    views: "600K views",
    viewsNum: 600000,
    time: "2 years ago",
    duration: "22:15",
    color: "#52525b",
  },
];

export const CATEGORIES = [
  "All",
  "Design",
  "Minimalism",
  "UI/UX",
  "React",
  "Tailwind",
  "Next.js",
  "Figma",
];
